[package]
name = "gpiosound"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
mio = { version = "0.7", features = ["os-poll", "os-ext"] }
timerfd = "1.2.0"
